/// Flutter icons Logotest2
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Logotest2
///      fonts:
///       - asset: fonts/Logotest2.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Logotest2 {
  Logotest2._();

  static const _kFontFam = 'Logotest2';

  static const IconData logotest2 = const IconData(0xe801, fontFamily: _kFontFam);
}
